package io.openmarket.organization.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.Set;

import static io.openmarket.config.OrgConfig.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = ORG_DDB_TABLE_NAME)
public class Organization {
    @NonNull
    @DynamoDBHashKey
    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_NAME)
    private String orgName;

    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_UID)
    private String orgUid;

    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_SLOGAN)
    private String orgSlogan;

    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_DESCRIPTION)
    private String orgDescription;

    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_PORTRAIT_S3KEY)
    private String orgPortraitS3Key;

    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_OWNER_ID)
    private String orgOwnerId;

    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_CURRENCIES)
    private Set<String> orgCurrencies;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_LAST_UPDATED_AT)
    private String lastUpdatedAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = ORG_DDB_ATTRIBUTE_CREATED_AT)
    private String createdAt;
}
