package io.openmarket.account.model;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.xspec.B;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Account {
    @DynamoDBHashKey(attributeName = "UserId")
    @DynamoDBAutoGeneratedKey
    private String userId;


    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "portraitKey")
    private String portraitS3Key;

    @DynamoDBAttribute(attributeName = "passwordHash")
    private String passwordHash;

    @DynamoDBAttribute(attributeName = "passwordSalt")
    private byte[] passwordSalt;

    @DynamoDBAttribute(attributeName = "displayName")
    private String displayName;

    @DynamoDBAttribute(attributeName = "coins")
    private Map<String, Double> coins;

    @DynamoDBAttribute(attributeName = "createAt")
    private String createAt;

    @DynamoDBAttribute(attributeName = "lastUpdatedAt")
    private String lastUpdatedAt;

}
