package io.openmarket.account.model;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import java.util.Date;
import java.util.Set;

import static io.openmarket.config.AccountConfig.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = USER_DDB_TABLE_NAME)
public class Account {
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_ID)
    private String userId;


    @DynamoDBHashKey(attributeName = USER_DDB_ATTRIBUTE_USERNAME)
    @NonNull private String username;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_PORTRAITKEY)
    private String portraitS3Key;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_PASSWORDHASH)
    @NonNull private String passwordHash;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_PASSWORDSALT)
    @NonNull private String passwordSalt;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_DISPLAYNAME)
    @NonNull private String displayName;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_CREATEAT)
    private Date createAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_LASTUPDATEDAT)
    private Date lastUpdatedAt;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_TAGS)
    private Set<String> tags;

}
