package io.openmarket.account.model;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.Map;

import static io.openmarket.config.AccountConfig.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = USER_DDB_TABLE_NAME)
public class Account {
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_ID)
    private String userId;


    @DynamoDBHashKey(attributeName = USER_DDB_ATTRIBUTE_USERNAME)
    private String username;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_PORTRAITKEY)
    private String portraitS3Key;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_PASSWORDHASH)
    private byte[] passwordHash;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_PASSWORDSALT)
    private byte[] passwordSalt;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_DISPLAYNAME)
    private String displayName;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_COINS)
    private Map<String, Double> coins;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_CREATEAT)
    private String createAt;

    @DynamoDBAttribute(attributeName = USER_DDB_ATTRIBUTE_LASTUPDATEDAT)
    private String lastUpdatedAt;

}
